### ISSUE TITLE
Data Catalog not loading with MySQL adapter for remote servers (using IP)

### ISSUE THREAD

**Issue by hiruthikj** [tconbeer/harlequin-mysql#2]
**Describe the bug**
I am trying to connect to a MySQL Server using IP as host with password, username, and database.
I am able to run queries, but data catalog doesnt load at all, or it gives error
![image](https://github.com/tconbeer/harlequin/assets/56921861/f47445fa-e771-460b-9c76-8a3f16ea9614)

**To Reproduce**
Try to connect to any MySQL remote server
Eg: You can try this credentials from a public MySQL Server (https://docs.rfam.org/en/latest/database.html)
harlequin -a mysql -h '193.62.194.222' -p 4497 -u rfamro --password "" --database Rfam
![image](https://github.com/tconbeer/harlequin-mysql/assets/56921861/91ceb735-244a-4c82-9947-c75792737817)

**Expected behavior**
Shows Catalog

**Actual behavior**
Sometimes it gives error as shown in screenshot or it doesnt load at all, but queries still can be run.

**Additional context**
What is the output of `harlequin --version`?
harlequin, version 1.9.0

Installed Adapters:
- duckdb, version 1.9.0
- sqlite, version 1.9.0
- mysql, version 0.1.0

(I am using ubuntu 23, with zsh shell. using mysql adapter for AWS RDS)

**Suggestion**
This can be useful to resolve: https://stackoverflow.com/questions/29772337/python-mysql-connector-unread-result-found-when-using-fetchone

**Comment by tconbeer** [comment]
I couldn't reproduce with MySQL on Azure with two databases and about 50 tables.

Maybe your user doesn't have permissions to select from the information schema? What happens when you run these queries?
```
show databases;
select table_name, table_type from information_schema.tables;
select column_name, data_type from information_schema.columns;
```

**Comment by hiruthikj** [comment]
Hi @tconbeer
I can run those, and am able to view catalog in other UIs like Dbeaver.

**Comment by hiruthikj** [comment]
Hi @tconbeer, you can try this credentials from a public MySQL Server (https://docs.rfam.org/en/latest/database.html)
harlequin -a mysql -h '193.62.194.222' -p 4497 -u rfamro --password "" --database Rfam

Same issue Persists
![image](https://github.com/tconbeer/harlequin-mysql/assets/56921861/0a15187a-16fe-4ec0-91be-a9061969e249)

**Comment by tconbeer** [comment]
Thanks so much for that - I'll dive in this week

**Comment by tconbeer** [comment]
I still can't reproduce -- things worked just fine for me, although it did take a while to populate the catalog. Can you run `pip list` and share all of the packages you have installed?
